main/default/objects/OAuth2__c/OAuth2__c.object-meta.xml
<CustomObject>
    <description>Used to store OAuth2 connections</description>
    <label>OAuth 2.0</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OAuth 2.0</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/objects/OAuth2__c/fields/Access_Token__c.field-meta.xml
<CustomField>
    <fullName>Access_Token__c</fullName>
    <description>This is the returned access token once successfully logged in with a client id and secret</description>
    <label>Access Token</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

main/default/objects/OAuth2__c/fields/Client_Id__c.field-meta.xml
<CustomField>
    <fullName>Client_Id__c</fullName>
    <description>The client id given by apps that allow oauth</description>
    <label>Client Id</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

main/default/objects/OAuth2__c/fields/Client_Secret__c.field-meta.xml
<CustomField>
    <fullName>Client_Secret__c</fullName>
    <description>The client secret given by apps that allow oauth</description>
    <label>Client Secret</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

main/default/objects/OAuth2__c/fields/Expires_In__c.field-meta.xml
<CustomField>
    <fullName>Expires_In__c</fullName>
    <description>The amount of time in seconds before the access token expires.</description>
    <label>Expires In (Seconds)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

main/default/classes/OAuthController.cls
public with sharing class OAuthController 
{
    @AuraEnabled
    public static Boolean save(string oAuthName, Map<String, Object> params)
    {
        try 
        {
            OAuth2__c oAuth = getNewestOAuthByName(oAuthName);
            System.debug('oAuth: ' + oAuth);

            if (oAuth == null)
            {
                oAuth = new OAuth2__c(); 
                oAuth.Name = oAuthName;
            }

            // Make them custom labels - maybe
            oAuth.Client_Id__c = (string) params.get('clientId');
            oAuth.Client_Secret__c = (string) params.get('clientSecret');

            upsert oAuth;
        } 
        catch (AuraHandledException e) 
        {
            throw new AuraHandledException(e.getMessage());
        }

        return true;
    }

    @AuraEnabled
    public static OAuth2__c getNewestOAuthByName(string oAuthName)
    {
        OAuth2__c oAuth;

        try 
        {
            oAuth = 
            [
                SELECT
                    Client_Id__c,
                    Client_Secret__c,
                    Expires_In__c,
                    Access_Token__c
                FROM OAuth2__c 
                WHERE Name =: oAuthName 
                ORDER BY CreatedDate DESC
                LIMIT 1
            ];
        } 
        catch (Exception e) 
        {
            return null;
        } 
        
        return oAuth;
    }
}